version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - export IMAGE_REFERENCE="$REGISTRY_URL/$REPOSITORY_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - |
        echo "{\"buildNumber\": $CODEBUILD_BUILD_NUMBER, \"builtAt\": $CODEBUILD_START_TIME, \"sourceVersion\": \"$CODEBUILD_RESOLVED_SOURCE_VERSION\"}" > buildMeta.json
  build:
    commands:
      - docker build -t $IMAGE_REFERENCE .
      - aws ecr get-login-password | docker login --username AWS --password-stdin $REGISTRY_URL
      - docker push $IMAGE_REFERENCE
      - |
        echo "{\"Parameters\": {\"ContainerImage\": \"$IMAGE_REFERENCE\"}}" > cfnConfiguration.json
artifacts:
  name: cfnConfiguration
  files:
    - cfnConfiguration.json
